### ISSUE TITLE
Ime repozitorija

### ISSUE THREAD

**Issue by jaanos** [JakobSvetina/Aproksimacija-povprecne-razdalje#1]
@JakobSvetina, svetujem, da ima repozitorij bolj pomenljivo ime, npr. `Aproksimacija-povprecne-razdalje`. Ime spremeniš tako, da zgoraj klikneš na *Settings*, nato pa spremeniš ime pod **Repository name**.

**Comment by JakobSvetina** [comment]
Hvala za opozorilo, sem spremenil ime.
